# Generated by Django 4.2.5 on 2023-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("Payment", "Payment"), ("Fine", "Fine")], max_length=7
            ),
        ),
    ]
