# Generated by Django 4.2.5 on 2023-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                ("author", models.CharField(max_length=63)),
                (
                    "cover",
                    models.CharField(
                        choices=[("H", "Hard"), ("S", "Soft")], max_length=1
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=0)),
                ("daily_free", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
